---
title: "SARS-COV2 GENOTYPING"
author: "Compiled by Stephen Kanyerezi"
date: "2022-07-22"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
---

\newpage

```{r setup, include=FALSE}
setwd("~/SARS_data_analysis/") # set the working directory

getwd() # confirm the working directory
list.files() # check the contents of the directory

# Load the packages needed
library(tidyverse)
library(xlsx)

data1 <- read.xlsx("./geno_sars.xlsx", sheetIndex = 1) # read in the data
#data1$Pangolian.lineage[data1$Pangolian.lineage == "BA.1.1.15" | data1$Pangolian.lineage == "BA.1.1.4" | data1$Pangolian.lineage == "BA.1.15" | data1$Pangolian.lineage == "BA.1.1.1" | data1$Pangolian.lineage == "BA.1.1.18" | data1$Pangolian.lineage == "BA.1.1.2" | data1$Pangolian.lineage == "BA.1.113"] <- "BA.1.1"

# data1$Pangolian.lineage[data1$Pangolian.lineage == "BA.1.617.2" | data1$Pangolian.lineage == "BA.1.2" | data1$Pangolian.lineage == "BA.1.9" | data1$Pangolian.lineage == "B.1.617.2" | data1$Pangolian.lineage == "BA.1.14.1" | data1$Pangolian.lineage == "BA.1.13"] <- "BA.1"

# data1$Pangolian.lineage[data1$Pangolian.lineage == "BA.5.2.1"] <- "BA.5"

# data1$Pangolian.lineage[data1$Pangolian.lineage == "BA.2.2"] <- "BA.2"

# data1$Pangolian.lineage[data1$Pangolian.lineage == "AY.46.4"] <- "AY.46"

# data1$Pangolian.lineage[data1$Pangolian.lineage == "BA.4.1"] <- "BA.4"
```

# Prevalence

## Prevalence by Pango lineage

```{r pang, echo=FALSE, warning=FALSE, message=FALSE}
data2 <- filter(data1, Pangolian.lineage != "Unassigned") # exclude the unassigned samples
ggplot(data2, aes(x = reorder(Pangolian.lineage, Pangolian.lineage, length), fill = Pangolian.lineage)) +
  geom_bar(width = 0.9) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("Pango lineage") +
  geom_text(stat = 'count', aes(label=..count..), vjust=-0.5) # do the bar plot
  #geom_text(stat = 'count', aes(label=..count..), vjust=0) +
  #coord_flip()
#View(data1)

```

## Prevalence of nextclade lineage

```{r next, echo=FALSE, message=FALSE, warning=FALSE}
data3 <- filter(data1, Nextclade.clade != "Unassigned") # remove the unassigned samples for nextclade
ggplot(data3, aes(x = reorder(Nextclade.clade, Nextclade.clade, length), fill = Nextclade.clade)) +
  geom_bar(width = 0.9) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 1)) +
  xlab("Nextclade lineage") +
  geom_text(stat = 'count', aes(label=..count..), vjust=-0.5) #+
  #coord_flip() # do the bar plotting
```

## Prevalence for spike variants

```{r spike, echo=FALSE, message=FALSE, warning=FALSE}
data4 <- filter(data1, Spike.Variant != "Unassigned") # remove the unassigned samples for the spike variants
ggplot(data4, aes(x = reorder(Spike.Variant, Spike.Variant, length), fill = Spike.Variant)) +
  geom_bar(width = 0.4) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 1)) +
  xlab("Spike Variant") +
  geom_text(stat = 'count', aes(label=..count..), vjust=-0.5) #+
  #coord_flip()

```

# Monthly trends

## Monthly trends of Pango lineages

```{r panmon, echo=FALSE, warning=FALSE, message=FALSE}
year <- filter(data1, Year.of.Collection != "unknown") # remove samples with unknown year of collection
yearp <- filter(year, Pangolian.lineage != "Unassigned") # remove samples whose pangolin lineage is unassigned
yearp$Month.of.Collection <- toupper(yearp$Month.of.Collection) # convert the month of collection to upper case
yearp$Month.of.Collection[yearp$Month.of.Collection == "JUN"] <- "JUNE" # convert "JUN " values to "JUNE"
yearp <- filter(yearp, Year.of.Collection == "2022") # retain samples collected in 2022 only
level_order <- factor(yearp$Month.of.Collection, levels = c("JAN", "FEB", "MAY", "JUNE", "JULY", "DEC")) # create levels for months so that the plot shows the exact sequence and not follow alphabetical order
ggplot(yearp, aes(x = level_order, fill = Pangolian.lineage)) +
  geom_bar(width = 0.9) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("Pango lineage") #+
  #geom_text(stat = 'count', aes(label=..count..), vjust=0) +
  #coord_flip() +
  # facet_wrap(~Year.of.Collection) # do the plotting

```

## Monthly trends of Nextclade lineages

```{r nextmon, echo=FALSE, warning=FALSE, message=FALSE}
# year <- filter(data1, Year.of.Collection != "unknown")
yearn <- filter(year, Nextclade.clade != "Unassigned") # remove samples whose nextclade lineage is unassigned
yearn$Month.of.Collection <- toupper(yearn$Month.of.Collection) # convert the months to upper case
yearn$Month.of.Collection[yearn$Month.of.Collection == "JUN"] <- "JUNE" # convert "JUN " to "JUNE" values
yearn <- filter(yearn, Year.of.Collection == "2022") # retain only samples collected in 2022
level_order <- factor(yearn$Month.of.Collection, levels = c("JAN", "FEB", "MAY", "JUNE", "JULY", "DEC")) # convert the month of collection to factors and create levels for a sensible display
#yearn <- filter(yearn, Year.of.Collection == "2022")
ggplot(yearn, aes(x = level_order, fill = Nextclade.clade)) +
  geom_bar(width = 0.9) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("Nextclade lineage") #+
  #geom_text(stat = 'count', aes(label=..count..), vjust=0) +
  #coord_flip() +
  #facet_wrap(~Year.of.Collection)
# ggplot(yearn, aes(x = reorder(Nextclade.clade, Nextclade.clade, length), fill = Nextclade.clade)) +
#   geom_bar(width = 1) +
#   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
#   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
#   xlab("Nextclade lineage") +
  #geom_text(stat = 'count', aes(label=..count..), vjust=0) +
  #coord_flip() +
#  facet_wrap(Month.of.Collection~Year.of.Collection)
```

## Monthly trends of spike variants

```{r spimon, echo=FALSE, warning=FALSE, message=FALSE}
years <- filter(year, Spike.Variant != "Unassigned") # remove samples whose spike variant is unassigned
years$Month.of.Collection <- toupper(years$Month.of.Collection) # convert the month of collection to upper case
years$Month.of.Collection[years$Month.of.Collection == "JUN"] <- "JUNE" # replace "JUN" values with "JUNE"
ggplot(years, aes(x = reorder(Spike.Variant, Spike.Variant, length), fill = Month.of.Collection)) +
  geom_bar(width = 0.5) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("Spike Variant") +
  geom_text(stat = 'count', aes(label=..count..), vjust=0) +
  coord_flip() +
  facet_wrap(~Year.of.Collection)

```